### ISSUE TITLE
[transfer] documentation is poor

### ISSUE THREAD

**Issue by tidwall** [tile38/tile38.github.io#33]
Transferred from https://github.com/tidwall/tile38/issues/590

> hi,
> 
> I think this is an extraordinary project and for this I congratulate you
> 
> the command list is perfect(although references to redis could be inserted)
and also the Geofencing section is interesting
> 
> but the basic documentation should be more extensive, for example it would be useful:
> 
> a glossary with basic terms (key, channel ...)
general architecture of the project
a section dedicated to the cli client
I would like to contribute but I lack these bases
> 
> best regards
> Stef

**Comment by stefanocudini** [comment]
tnks

**Comment by tidwall** [comment]
I'm closing this for now.
The docs may not be up be 100% up to snuff for all topics, but it's been getting better since this issue was originally filed, including site updates that allow for public edits.
Thanks for your feedback.
