### ISSUE TITLE
Generated source out of date?

### ISSUE THREAD

**Issue by Lars-Meijer** [tile38/tile38.github.io#5]
When I run ./build.sh on master (head) git marks a lot of files as changed, so some files might not be up to date.
I think the files generated by building eg (/topics, /commands) etc. should not be in git anyway, and the output of build.sh should probably in a different folder.

**Comment by tidwall** [comment]
I agree that it's not ideal but at the moment the tile38.com domain uses Github pages and the site needs the /commands and /topics directories to be at the root level. It *should* be OK to commit the changed files. 

If the site looks good locally when running `./build.sh -port 8080` then commit and push.

At some point I would like to move to a better static generator, this project was a hack I put together over a weekend.

**Comment by tidwall** [comment]
This site has been totally updated to use a Docusaurus as the static generator.

Now all source files are in `master` and published files are in `gh-pages`.

I'm closing this issue, but feel free to reopen if you have more suggestions.

Thanks!
